### ISSUE TITLE
Support PHP 8.1, drop 7.3

### ISSUE THREAD

**Issue by korelstar** [ChristophWurst/nextcloud_composer#14]
As far as I can see, Nextcloud 24 will support PHP 8.1 - at least the master branch has support for it: https://github.com/nextcloud/server/commit/72baee96988bbd9d3f7d68a90bf716008946000f

However, this composer package does not support PHP 8.1 yet. Please add support for it and publish it :-)

**Comment by ChristophWurst** [comment]
Makes sense! Could you send a PR please?

**Comment by ChristophWurst** [comment]
7.3 should also be dropped as per https://github.com/nextcloud/server/pull/29286

**Comment by korelstar** [comment]
Sorry, I'm not aware on how this repository works. Honestly, I have no idea where to do such a change and how to publish a new version. Maybe you could do it?

**Comment by ChristophWurst** [comment]
No worries. https://github.com/ChristophWurst/nextcloud_composer/blob/07ca35fed2423e4ee89bb1da98a637fd0f89d272/composer.json#L13 is the only line that needs change. I'll take care of the release.

**Comment by ChristophWurst** [comment]
https://packagist.org/packages/christophwurst/nextcloud#dev-master can be used with 8.1
