### ISSUE TITLE
nextcloud api package documentation

### ISSUE THREAD

**Issue by thalgrim** [ChristophWurst/nextcloud_composer#4]
Hello, I'm a young developper,
I'm developping an application with symfony 4.3. And I need to communicate with Nextcloud, so I installed your nextcloud api package with composer, but i don't find any documentation tu use it.
Do you have any documentation which can help me?

**Comment by ChristophWurst** [comment]
This is not what this package does. It's the API Nextcloud apps use when communicating with the server code.

For external apps you have to use the OCS APIs or WebDAV.
