### ISSUE TITLE
release for 20-beta1

### ISSUE THREAD

**Issue by korelstar** [ChristophWurst/nextcloud_composer#5]
Hey @ChristophWurst ,

could you please add a release for Nextcloud 20-beta1? This would be nice in order to check implementation of new bootstapping, dashboards widgets and unified search ...

Thanks!

**Comment by ChristophWurst** [comment]
https://packagist.org/packages/christophwurst/nextcloud#v20.0.0-beta1 done :)

**Comment by korelstar** [comment]
Nice, thanks!
